# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname pois2
#' @export
dpois2 <- function(x1, x2, lambda1, lambda2, lambda3) {
    .Call('_pois2_dpois2', PACKAGE = 'pois2', x1, x2, lambda1, lambda2, lambda3)
}

